### ISSUE TITLE
Vote for Blahaj

### ISSUE THREAD

**Issue by UnHolds** [fsinf/poster#10]
Blahaj wants to kick-start its political campaign and we want to help it. 
Therefore, we need to design a poster to spread the message "VOTE 4 Blahaj".

Other reasons:
* Trans-Awareness
* Showing that we are an open and welcoming space
* Funny

**Comment by UnHolds** [comment]
Merged via #11

**Comment by ambiso** [comment]
I have thoroughly analyzed the political stance of Blåhaj and have been convinced by their arguments. This only leaves me with one question not answered by the poster: How do I vote for Blåhaj?
